### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by joelaw9** [Darkhax-Minecraft/GYTH#10] opened 2017-03-19 23:49 UTC
I was playing around with a diamond modular tank (SF3 3.0.8 && GYTH 2.0.0.23) and my client crashed. The specific action I was doing at the time was breaking an empty diamond modular tank with an empty hand.

[crash-2017-03-19_18.32.27-client.txt](https://github.com/Darkhax-Minecraft/GYTH/files/853669/crash-2017-03-19_18.32.27-client.txt)

**Comment by Gunner76th** [comment] 2017-03-20 22:53
This is a duplicate of https://github.com/Darkhax-Minecraft/GYTH/issues/9

**Comment by Darkhax** [comment] 2017-03-20 23:27
Thanks for reporting, as stated this is a duplicate of #9 A fix will be out soon enough.

**Closed as completed by Darkhax** 2017-03-20 23:27 UTC
Labels: duplicate
